### ISSUE TITLE
Flagged as Trojan by Defender

### ISSUE THREAD

**Issue by PerpetualCycle** [CoolCmd/TestMem5#1]

**Comment by CoolCmd** [comment]
Some antiviruses, including those built into Windows, may claim that this program contains a virus. This is a false positive. Stupid heuristic antivirus analyzers do not like programs written in Assembly language.

**Comment by htmlprogrammist** [comment]
![image](https://github.com/CoolCmd/TestMem5/assets/60363270/dd6dcc50-2ea0-4604-a486-6cea8cd85e2b)

It's up to you whether to use this program or not

**Comment by Th3EvilGod** [comment]
I still get an error with windows defender

**Comment by Anton-V-K** [comment]
Microsoft's antivirus still doesn't like this nice tiny program :(
- K7AntiVirus - Riskware ( 00584baa1 )
- K7GW - Riskware ( 00584baa1 )
- Microsoft - PUA:Win32/Caypnamer.A!ml
- Sangfor Engine Zero - PUP.Win32.Agent.V4yb

Ref: [VirusTotal report for 0.13.1](https://www.virustotal.com/gui/file/05ffb5bbaa0c2243bf25664049c7aa3615a77bd5036497ef845fc8ed50128c12)
